/**
 * at.js → Web SDK compatibility shim generator (v1.4).
 *
 * Produces a standalone runtime JS file that defines `window.adobe.target.*`
 * with the at.js 2.x public surface, but routes every call through
 * `alloy("sendEvent", ...)` under the hood. Lets a site keep its existing
 * `getOffer/applyOffer/getOffers/applyOffers/trackEvent/triggerView` call
 * sites working while the underlying delivery is Web SDK — the
 * differentiator that lets large enterprise sites cut over incrementally
 * instead of touching every mbox call site in one PR.
 *
 * Generated artifact is ~200 lines of vanilla JS (no deps, IIFE-wrapped,
 * ES2017+ syntax — async/Promise required because alloy is async). The
 * generator templates a few config values from the analysis report:
 *   • clientCode (used as log prefix only)
 *   • known mbox catalog (warn on typos at call sites)
 *
 * Out of scope for v1 (defer):
 *   • at.js 1.x `mboxCreate / mboxDefine / mboxUpdate` (legacy DOM-replace)
 *   • Custom selector engines (CSS selectors only)
 *   • Lifecycle hooks (init.complete, etc.)
 *   • A4T linkage on the analytics side (separate concern)
 */

import type { AtjsAnalysisReport } from "./atjs-analysis.js";

// ── Types ───────────────────────────────────────────────────
export interface ShimOptions {
  /** Override the clientCode the analysis report extracted. */
  clientCode?: string;
  /** Override the mbox catalog (defaults to the union of all detected mboxes). */
  knownMboxes?: string[];
  /** Default false. When true, the shim emits console.log on every call. */
  debug?: boolean;
  /** Default "alloy". The global name of the Web SDK instance. */
  alloyInstance?: string;
}

export interface CompatShimArtifact {
  js: string;
  instructions: string;
  metadata: {
    client_code: string | null;
    mbox_count: number;
    alloy_instance: string;
    debug_default: boolean;
    generated_at: string;
    estimated_size_bytes: number;
  };
}

// ── Generator ───────────────────────────────────────────────
export function generateAtjsCompatShim(
  report: AtjsAnalysisReport,
  options: ShimOptions = {}
): CompatShimArtifact {
  const clientCode =
    options.clientCode ?? report.atjs.client_code ?? "unknown";
  const mboxCatalog =
    options.knownMboxes ?? report.recommended_setup.decisionScopes_default;
  const debugDefault = options.debug === true;
  const alloyInstance = options.alloyInstance ?? "alloy";

  const js = renderShimJs({
    clientCode,
    mboxCatalog,
    debugDefault,
    alloyInstance,
  });

  const instructions = renderInstructions({
    clientCode,
    mboxCount: mboxCatalog.length,
    alloyInstance,
  });

  return {
    js,
    instructions,
    metadata: {
      client_code: report.atjs.client_code ?? null,
      mbox_count: mboxCatalog.length,
      alloy_instance: alloyInstance,
      debug_default: debugDefault,
      generated_at: new Date().toISOString(),
      estimated_size_bytes: js.length,
    },
  };
}

// ── Shim template ───────────────────────────────────────────
interface ShimConfig {
  clientCode: string;
  mboxCatalog: string[];
  debugDefault: boolean;
  alloyInstance: string;
}

function renderShimJs(cfg: ShimConfig): string {
  const generatedAt = new Date().toISOString();
  const catalogJson = JSON.stringify(cfg.mboxCatalog);
  return `/**
 * target-atjs-shim — Adobe at.js → Web SDK compatibility shim
 *
 * Generated by target-websdk-foundation v1.4 at ${generatedAt}.
 *
 * Defines the at.js 2.x public surface (\`window.adobe.target.*\`) but
 * routes every call through Adobe Web SDK's \`${cfg.alloyInstance}("sendEvent", ...)\`.
 * Drop this in your <head> AFTER the Web SDK launch script. Existing
 * \`getOffer\`/\`applyOffer\`/\`trackEvent\`/etc. call sites keep working;
 * personalization decisions now come from Edge Network instead of at.js.
 *
 * Debug: append \`?target_shim_debug=1\` to any URL to enable verbose
 * console logging from the shim (the underlying alloy is unaffected).
 *
 * Limitations:
 *   • This is a TRANSITIONAL artifact. Retire it once all at.js call
 *     sites have been refactored to use \`${cfg.alloyInstance}\` directly.
 *   • at.js 1.x globals (\`mboxCreate\`, \`mboxDefine\`, \`mboxUpdate\`) are
 *     stubbed as warning-only no-ops. Replace them in your codebase.
 *   • JSON offers are dispatched as \`targetShim:jsonOffer\` CustomEvent
 *     on \`document\` — your site script must listen.
 *   • A4T linkage on the Analytics side must be configured separately
 *     via the Datastream's Analytics service.
 */
(function () {
  "use strict";

  // ── Configuration ───────────────────────────────────────────
  var CONFIG = {
    clientCode: ${JSON.stringify(cfg.clientCode)},
    knownMboxes: ${catalogJson},
    debug: ${cfg.debugDefault ? "true" : "false"},
    alloyInstance: ${JSON.stringify(cfg.alloyInstance)}
  };

  // ── Diagnostics ─────────────────────────────────────────────
  function isDebug() {
    if (CONFIG.debug) return true;
    try { return /[?&]target_shim_debug=1\\b/.test(window.location.search); }
    catch (e) { return false; }
  }
  function log(level, msg, data) {
    if (!isDebug() && level === "debug") return;
    var prefix = "[target-atjs-shim:" + CONFIG.clientCode + "]";
    var fn = level === "warn" ? "warn" :
             level === "error" ? "error" :
             "log";
    if (data !== undefined) console[fn](prefix, msg, data);
    else console[fn](prefix, msg);
  }

  function warnUnknownMbox(mbox) {
    if (CONFIG.knownMboxes.length === 0) return;
    if (CONFIG.knownMboxes.indexOf(mbox) === -1) {
      log("warn",
        "getOffer/applyOffer called for mbox NOT in catalog: " + mbox +
        ". Catalog: " + CONFIG.knownMboxes.join(", ") +
        ". Either a typo, an mbox missed at analysis time, or a runtime-registered mbox.");
    }
  }

  // ── Alloy wrapper ───────────────────────────────────────────
  function getAlloy() { return window[CONFIG.alloyInstance]; }

  function alloyEvent(payload) {
    var fn = getAlloy();
    if (typeof fn !== "function") {
      log("error",
        "Web SDK instance \\"" + CONFIG.alloyInstance + "\\" not found on window. " +
        "Confirm the Tags property's adobe-alloy extension is installed and the Web SDK script tag is in <head> BEFORE this shim.");
      return Promise.reject(new Error("alloy not loaded"));
    }
    return fn("sendEvent", payload);
  }

  // ── Schema translation ─────────────────────────────────────
  var SCHEMA = {
    HTML: "https://ns.adobe.com/personalization/html-content-item",
    REDIRECT: "https://ns.adobe.com/personalization/redirect-item",
    JSON: "https://ns.adobe.com/personalization/json-content-item",
    DEFAULT: "https://ns.adobe.com/personalization/default-content-item"
  };

  function itemToOffer(item, scope) {
    var data = (item && item.data) || {};
    if (item.schema === SCHEMA.HTML) {
      return {
        type: "html",
        content: data.content || "",
        selector: data.selector,
        responseTokens: item.meta || {}
      };
    }
    if (item.schema === SCHEMA.REDIRECT) {
      return { type: "redirect", content: data.url || "" };
    }
    if (item.schema === SCHEMA.JSON) {
      return { type: "json", content: data.content || null };
    }
    if (item.schema === SCHEMA.DEFAULT) {
      return { type: "default", content: "" };
    }
    return { type: "unknown", content: data.content || "", schema: item.schema };
  }

  function propositionsToOffers(propositions, scope) {
    var offers = [];
    if (!propositions) return offers;
    for (var i = 0; i < propositions.length; i++) {
      var p = propositions[i];
      if (p.scope !== scope) continue;
      var items = p.items || [];
      for (var j = 0; j < items.length; j++) {
        offers.push(itemToOffer(items[j], scope));
      }
    }
    return offers;
  }

  // ── DOM mutation for applyOffer ────────────────────────────
  function applyOneOffer(offer, fallbackSelector) {
    if (offer.type === "html") {
      var sel = offer.selector || fallbackSelector;
      if (!sel) {
        log("warn", "applyOffer: HTML offer has no selector", offer);
        return false;
      }
      try {
        var el = document.querySelector(sel);
        if (!el) {
          log("warn", "applyOffer: selector \\"" + sel + "\\" matched no element");
          return false;
        }
        el.innerHTML = offer.content;
        return true;
      } catch (e) {
        log("error", "applyOffer: selector \\"" + sel + "\\" threw", e);
        return false;
      }
    }
    if (offer.type === "redirect") {
      if (offer.content) {
        log("debug", "applyOffer: redirecting to " + offer.content);
        window.location.href = offer.content;
        return true;
      }
      return false;
    }
    if (offer.type === "json") {
      try {
        var ev = new CustomEvent("targetShim:jsonOffer", {
          detail: { content: offer.content }
        });
        document.dispatchEvent(ev);
        return true;
      } catch (e) { log("error", "applyOffer: JSON dispatch failed", e); return false; }
    }
    if (offer.type === "default") return true;
    log("warn", "applyOffer: unknown offer type", offer);
    return false;
  }

  // ── Public API: at.js 2.x ──────────────────────────────────
  function getOffer(opts) {
    opts = opts || {};
    if (!opts.mbox) {
      log("error", "getOffer called without mbox", opts);
      if (typeof opts.error === "function") opts.error({ status: 400, message: "mbox required" });
      return;
    }
    warnUnknownMbox(opts.mbox);
    log("debug", "getOffer(" + opts.mbox + ")");
    alloyEvent({
      decisionScopes: [opts.mbox],
      renderDecisions: false,
      data: opts.params || undefined
    }).then(function (result) {
      var offers = propositionsToOffers(
        (result && (result.propositions || (result.decisions || []))) || [],
        opts.mbox
      );
      log("debug", "getOffer(" + opts.mbox + ") → " + offers.length + " offer(s)", offers);
      if (typeof opts.success === "function") opts.success(offers);
    }, function (err) {
      log("error", "getOffer(" + opts.mbox + ") failed", err);
      if (typeof opts.error === "function") opts.error(err);
    });
  }

  function applyOffer(opts) {
    opts = opts || {};
    var offers = opts.offer || opts.offers || [];
    if (offers.length === 0) {
      log("debug", "applyOffer: no offers to apply");
      return;
    }
    warnUnknownMbox(opts.mbox);
    var applied = 0;
    for (var i = 0; i < offers.length; i++) {
      if (applyOneOffer(offers[i], opts.selector)) applied++;
    }
    log("debug", "applyOffer(" + (opts.mbox || "—") + "): " + applied + "/" + offers.length + " applied");
  }

  function getOffers(opts) {
    opts = opts || {};
    var requests = (opts.request && opts.request.execute && opts.request.execute.mboxes) || [];
    if (requests.length === 0) {
      log("error", "getOffers called without request.execute.mboxes[]", opts);
      if (typeof opts.error === "function") opts.error({ status: 400, message: "mboxes required" });
      return;
    }
    var scopes = requests.map(function (m) { warnUnknownMbox(m.name); return m.name; });
    log("debug", "getOffers(" + scopes.join(",") + ")");
    alloyEvent({ decisionScopes: scopes, renderDecisions: false })
      .then(function (result) {
        var atjsResponse = { execute: { mboxes: [] } };
        var props = (result && (result.propositions || result.decisions)) || [];
        for (var i = 0; i < scopes.length; i++) {
          atjsResponse.execute.mboxes.push({
            name: scopes[i],
            options: propositionsToOffers(props, scopes[i])
          });
        }
        if (typeof opts.success === "function") opts.success(atjsResponse);
      }, function (err) {
        log("error", "getOffers failed", err);
        if (typeof opts.error === "function") opts.error(err);
      });
  }

  function applyOffers(opts) {
    opts = opts || {};
    var responses = (opts.response && opts.response.execute && opts.response.execute.mboxes) || [];
    for (var i = 0; i < responses.length; i++) {
      applyOffer({ mbox: responses[i].name, offer: responses[i].options || [] });
    }
  }

  function getOfferAndApply(opts) {
    opts = opts || {};
    getOffer({
      mbox: opts.mbox,
      params: opts.params,
      success: function (offers) { applyOffer({ mbox: opts.mbox, offer: offers, selector: opts.selector }); if (typeof opts.success === "function") opts.success(offers); },
      error: opts.error
    });
  }

  function trackEvent(opts) {
    opts = opts || {};
    log("debug", "trackEvent", opts);
    alloyEvent({
      type: opts.type || "decisioning.propositionInteract",
      xdm: opts.params || {},
      data: opts.params || undefined
    }).catch(function (err) { log("error", "trackEvent failed", err); });
  }

  function triggerView(viewName, opts) {
    opts = opts || {};
    log("debug", "triggerView(" + viewName + ")");
    alloyEvent({
      renderDecisions: true,
      xdm: { eventType: "decisioning.propositionFetch", web: { webPageDetails: { viewName: viewName } } }
    }).catch(function (err) { log("error", "triggerView failed", err); });
  }

  // ── at.js 1.x legacy stubs (warn-only) ──────────────────────
  function legacyStub(name) {
    return function () {
      log("warn",
        name + "() is at.js 1.x legacy and not supported by this shim. " +
        "Replace these call sites with adobe.target.getOffer/applyOffer (at.js 2.x style).");
    };
  }

  // ── Bind to globals ─────────────────────────────────────────
  if (!window.adobe) window.adobe = {};
  if (!window.adobe.target) window.adobe.target = {};
  window.adobe.target.getOffer = getOffer;
  window.adobe.target.applyOffer = applyOffer;
  window.adobe.target.getOffers = getOffers;
  window.adobe.target.applyOffers = applyOffers;
  window.adobe.target.getOfferAndApply = getOfferAndApply;
  window.adobe.target.trackEvent = trackEvent;
  window.adobe.target.triggerView = triggerView;
  // init() is a no-op — Web SDK handles initialization
  window.adobe.target.init = function () { log("debug", "init() — no-op under shim"); };

  // at.js 1.x globals
  if (typeof window.mboxCreate === "undefined") window.mboxCreate = legacyStub("mboxCreate");
  if (typeof window.mboxDefine === "undefined") window.mboxDefine = legacyStub("mboxDefine");
  if (typeof window.mboxUpdate === "undefined") window.mboxUpdate = legacyStub("mboxUpdate");

  log("debug", "shim ready · " + CONFIG.knownMboxes.length + " mbox(es) in catalog · alloy=\\"" + CONFIG.alloyInstance + "\\"");
})();
`;
}

function renderInstructions(opts: {
  clientCode: string;
  mboxCount: number;
  alloyInstance: string;
}): string {
  return `# at.js → Web SDK compatibility shim — deployment

Generated for client: \`${opts.clientCode}\` · catalog: ${opts.mboxCount} mbox(es) · alloy global: \`${opts.alloyInstance}\`

## What this is

A drop-in JS file that defines the at.js 2.x public surface (\`window.adobe.target.*\`) but routes every call through the Adobe Web SDK (\`${opts.alloyInstance}()\`) under the hood. Your existing \`getOffer\` / \`applyOffer\` / \`trackEvent\` / \`triggerView\` call sites keep working — personalization decisions come from Edge Network instead of at.js.

## Where to put it

1. **Save the \`js\` field of the response** to a file in your codebase, e.g. \`assets/js/target-atjs-shim.js\`.
2. **Add a \`<script>\` tag** to your site \`<head>\`, AFTER the Web SDK Tags launch script:

\`\`\`html
<head>
  <!-- prehide (from setup_target_websdk) -->
  <style>body {opacity: 0}</style>
  <!-- Web SDK / Tags launch library -->
  <script src="https://assets.adobedtm.com/.../launch-...development.min.js" async></script>
  <!-- at.js compatibility shim -->
  <script src="/assets/js/target-atjs-shim.js"></script>
  <!-- ... your existing at.js script tag CAN be removed at this point ... -->
</head>
\`\`\`

3. **Remove the existing at.js script tag** (\`assets.adobedtm.com/.../at.js-X.Y.Z.min.js\` or \`cdn.tt.omtrdc.net/at.js-...\`). The shim provides the same API surface — keeping both creates a conflict.

## Verification

1. Load the page with \`?target_shim_debug=1\` in the URL.
2. Open the browser console. You should see:
   - \`[target-atjs-shim:${opts.clientCode}] shim ready · ${opts.mboxCount} mbox(es) in catalog · alloy="${opts.alloyInstance}"\`
   - A \`getOffer/applyOffer/etc.\` log line on each at.js call site invocation.
3. If you see \`Web SDK instance "${opts.alloyInstance}" not found on window\` — the shim is loading before \`${opts.alloyInstance}\` is initialized. Move the shim script tag AFTER the Tags launch script.
4. If you see \`getOffer/applyOffer called for mbox NOT in catalog: <name>\` — either it's a typo, a runtime-registered mbox the analyzer didn't catch, or a stale call site. Re-run \`analyze_atjs_implementation\` with \`knownMboxes\` including this name to refresh the catalog.

## Limitations

- **JSON offers** are dispatched as a \`targetShim:jsonOffer\` CustomEvent on \`document\`. Your site script must listen if you use JSON offers:
  \`\`\`js
  document.addEventListener("targetShim:jsonOffer", function (e) { /* e.detail.content */ });
  \`\`\`
- **at.js 1.x globals** (\`mboxCreate\`, \`mboxDefine\`, \`mboxUpdate\`) are stubbed as warning-only no-ops. Replace these call sites in your codebase.
- **A4T linkage** on the Analytics side must be configured separately via the Datastream's Analytics service (\`add_analytics_to_datastream\`).
- **Selector engines** — the shim uses \`document.querySelector\`. If your existing offers use custom selector engines, manually translate them to CSS3 selectors first.

## Retirement

This shim is a **transitional artifact**. Retire it once every \`adobe.target.*\` call site in your codebase has been refactored to call \`${opts.alloyInstance}("sendEvent", ...)\` directly. Track retirement by counting shim warnings in production browser logs — when warnings drop to zero for 30 days, the shim is safe to remove.
`;
}
